CREATE TABLE IF NOT EXISTS dice_games (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  game_code VARCHAR(8) NOT NULL UNIQUE,
  state_json JSON NOT NULL,
  dice_mode ENUM('real','digital') NOT NULL DEFAULT 'real',
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE dice_games ADD COLUMN IF NOT EXISTS host_name VARCHAR(100) NOT NULL DEFAULT '' AFTER game_code;
ALTER TABLE dice_games ADD COLUMN IF NOT EXISTS player_count TINYINT UNSIGNED NOT NULL DEFAULT 2 AFTER dice_mode;
ALTER TABLE dice_games ADD COLUMN IF NOT EXISTS status ENUM('active','finished') NOT NULL DEFAULT 'active' AFTER player_count;
